# action.yml
name: "Docker-Compose Publish"
author: "Darryl Mendillo"
description: "Publish all docker containers in docker-compose file"
branding:
  icon: "database"
  color: "red"
inputs:
  profiles:
    description: "Set docker compose --profile flag, for multiple profiles you can pass --profile foo --profile bar"
    required: false
    default: "--profile '*'"
  docker_compose_files:
    description: "docker-compose files to build and publish images from, multiple compose files can be passed -f foo.yml -f bar.yml"
    required: false
    default: '-f docker-compose.yml'
  repo_token:
    description: "Github Repo token"
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - id: publish
      run: ${{ github.action_path }}/src/publish.sh ${{ inputs.profiles }} ${{ inputs.docker_compose_files }} ${{ inputs.repo_token }}
      shell: bash
