# action.yml
name: "Docker Compose Build & Push"
author: "Arash Mo"
description: "Build, tag and push all services in docker-compose files"
branding:
  icon: "zap"
  color: "blue"
inputs:
  registery:
    description: "Registry address"
    required: false
    default: "ghcr.io"
  username:
    description: "Registry username"
    required: false
    default: ${{ github.actor }}
  password:
    description: "Registry password"
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}
  profiles:
    description: "Set docker compose --profile flag, for multiple profiles you can do like --profile foo --profile bar"
    required: false
    default: "--profile '*'"
  docker_compose_files:
    description: "docker-compose files to build and publish images from, multiple compose files can be passed as -f foo.yml -f bar.yml"
    required: false
    default: '-f docker-compose.yml'
runs:
  using: "composite"
  steps:
    - name: Log into registry ${{ inputs.registery }}
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ${{ inputs.registery }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - id: build
      run: docker compose ${{ inputs.docker_compose_files }} ${{ inputs.profiles }} build
      shell: bash
    - id: push
      run: docker compose ${{ inputs.docker_compose_files }} ${{ inputs.profiles }} push
      shell: bash
